# Generated by Django 3.2.9 on 2023-05-11 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_tgusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 10, 5, 45, 227236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 10, 5, 45, 227193, tzinfo=utc)),
        ),
    ]
